<template>
<div>
  <div>
    <h1>Welcome</h1>
  </div>
  <div>
    <h2>okpn</h2>
    <p>
      aaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaa<br>
    </p>
  </div>
  <div>
    <h2>Progress</h2>
    <p>
    </p>
  </div>

  <div>
    <h2>Skills</h2>
    <p>
    </p>
  </div>
  <div>
    <h2>Links</h2>
    <p>
    </p>
  </div>
</div>
</template>